### ISSUE TITLE
Integrate country performance page into the staging website and deploy

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#31]
* [x] Integrate latest code
* [x] Deploy live

**Comment by zelima** [comment]
@anuveyatsu Needs some more tidy  up

- [ ] Y axses is not visible and needs lable - 'Normalized counts' - hight priority
- [ ] smaller fonts for selectors - hight priority
- [ ] default country to be red and always stays in front of others
- [ ] Not delete lines when fetching new data for selected country

**Comment by rufuspollock** [comment]
FIXED. Live at http://cybergreen-staging.herokuapp.com/country/
