### ISSUE TITLE
UX tidying on country page performance graphs

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/cg-graphs#34]
@anuveyatsu Needs some more tidy  up

- [x] Y axis ticks are not visible and needs label - 'Normalized counts'
- [x] smaller fonts for selectors

Lower priority:

- [x] default country to be red and always stays in front of others (partially fixed, country is red but still overlapping)
- [x] Do not delete graph when fetching new data for a selected country (if anything just show a spinner)

**Comment by zelima** [comment]
FIXED
