### ISSUE TITLE
Configurable API endpoint

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/cg-graphs#35]
API endpoint is needed config for the app.

Should be passed in as a global e.g.

```
var CG_API_ENDPOINT = "//stats.cybergreen.net/api";
// or ...
var CG_API_ENDPOINT = "/api"; // if same domain ...
```

This way can be set for local testing and set by backend server in template for live site.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/39
