### ISSUE TITLE
Normalization is not explained anywhere

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/cg-graphs#43]
ISsue #22 talks about a new (non stats WG ) defined normalization. 
This is not documented anywhere on the public web site.
Also, it seems weird...
(see issue #22)

**Comment by rufuspollock** [comment]
@aaronkaplan would it be ok to keep the conversation in one place in #22 (and we close this in favour of that?)

**Comment by zelima** [comment]
DUPLICATE this is discussed here https://github.com/cybergreen-net/cg-graphs/issues/22#issuecomment-280603085
