### ISSUE TITLE
optimize js build size

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#51]
- [x] Optimize index.min.js build (Eg import from Plotly only needed)
- [x] like remove unused assignments and imports 
  - `'SET_VIEWS' is defined but never used`
  - `'spinnerStyle' is assigned a value but never used`

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/53

**Comment by rufuspollock** [comment]
@anuveyatsu good work and we've cut build size by 50%. Do you think there is anything else we can  remove here to get this down further? Are there any unneeded dependencies etc?
