### ISSUE TITLE
Improvements for Selector (dropdowns)

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#52]
#### AS page

Current look of selector also, see https://cybergreen-staging.herokuapp.com/country/united-kingdom/ 
![image](https://cloud.githubusercontent.com/assets/15143785/23247763/527e25b8-f9b5-11e6-8be2-517594e73eb9.png)

- [x] Drop down includes not only names, but numbers as well Eg: `1234 | uk defence research agency`
  - [x] Should be searchable with number as well (will be fixed automatically as parent issue is fixed)

#### for all selectors (home page, inside graphs...)
- [x] Loader (bouncing ball) should not appear after  
  - clicking `x` on the right, 
  - selecting `Select an AS`, 
  - type something --> clear everything

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/55

**Comment by zelima** [comment]
This occurred is not an issue for only AS page but for all dropdowns

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/56
