### ISSUE TITLE
Embed cg logo into graphs 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#63]
Graphs should have CyberGreen logo when exported if possible 

Maybe useful https://plot.ly/javascript/images/

**Comment by anuveyatsu** [comment]
@rufuspollock @shiweiart @zelima please take a look at different options of placing the logo in the graphs. Its size depends on plot size.
1) Logo with name placed vertically on the far right:
![image](https://cloud.githubusercontent.com/assets/17809581/23462587/a04775f8-feb8-11e6-9ab7-1d310a868791.png)

2) Logo without name placed in the centre of graph and with transparency level 0.2:
![image](https://cloud.githubusercontent.com/assets/17809581/23462653/de670236-feb8-11e6-8247-b93242dfc20a.png)

3) Logo with name placed on the top:
![image](https://cloud.githubusercontent.com/assets/17809581/23462677/f6fd0f7a-feb8-11e6-87d2-aa5b1c5d27a3.png)

**Comment by zelima** [comment]
I like second

**Comment by anuveyatsu** [comment]
FIXED https://github.com/cybergreen-net/cg-graphs/pull/68
