### ISSUE TITLE
UX improvements for graphs and selectors

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#72]
- [x] When selecting new AS from dropdown on `country/country-id` page it should be opened in new tab (currently redirecting)
- [x] Change title of Y axes on “normalized counts” => "count of infected devices"
- [x] ~~spinner does not appear when clicking on bar charts~~ irrelevant because now a page opens in a new tab
  - this also should be opened in new tab (this is done now)
- [x] Spinner location is not in the middle (it's already done need to update CSS in production site)
- [x] When typing to choose a new country a cursor appears not in the center of input element (in the graphs for country)  (done in CSS - need to update CSS in production site)
- [x] In `/country/country-id/asn/asn-id` page the first dropdown element in each graph is not displayed correctly:
![image](https://cloud.githubusercontent.com/assets/17809581/23888016/c5c656ea-08af-11e7-9a22-31d2f22bead4.png)

- [x] In `/country/country-id/asn/asn-id` page in a dropdown with ASs we want to have ID as well as AS name:
![image](https://cloud.githubusercontent.com/assets/17809581/23888065/1095638c-08b0-11e7-943e-2e519cba0eab.png)

**Comment by zelima** [comment]
FIXED

**Comment by anuveyatsu** [comment]
Added 2 new tasks in description
