### ISSUE TITLE
Implement Redux reducers 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#8]
Redux reducers for updating the Redux store, after triggering the actions

## Tasks

* [x] Write tests for Redux reducers
* [ ] Prepare fixtures
* [x] Implement Redux reducers
* [x] Pass tests

**Comment by rufuspollock** [comment]
@zelima is this ready for a PR or what is the state here? Should this move back to Icebox?

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/20
